name: Readme Checker

on:
  push:
    branches:
      - main
      - testing-1

jobs:
  readme-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Readme Checker!
        run: |
            ls -a 
          if [ ! -f README.md ]; then
            exit 1  
          fi
